### ISSUE TITLE
Trying to access the "settings" tab. 

### ISSUE THREAD

**Issue by ChieriOnTop** [uhKayla/Spectre#7]
Trying to access the settings tab after you're signed in brings you to a blank white page as of now, is this a work in progress or a not known error? 

https://github.com/uhKayla/Spectre/assets/149896794/5adae3c4-662d-400d-8d20-d2fe0548b5da

**Comment by uhKayla** [comment]
Sorry this is a work in progress, i should have documented this! I will leave this issue open until i fix it

**Comment by uhKayla** [comment]
Closed with #10 for now
